CREATE TABLE IF NOT EXISTS UserPerms
(
UserID      	INTEGER NOT NULL,
CogName  	VARCHAR(16) NOT NULL,
Permission  	INTEGER NOT NULL,
PRIMARY KEY (UserID, CogName),
FOREIGN KEY (UserID)
    REFERENCES Users(UserID)
    ON DELETE CASCADE,
FOREIGN KEY (CogName)
    REFERENCES Cogs(CogName)
    ON DELETE CASCADE
);
